project:
  title: "JAX-IDEM"
  type: website
  output-dir: docs

metadata-files:
  - reference/_sidebar.yml


bibliography: site/Bibliography.bib

execute:
  python: ".venv/bin/python"
  external: true

format:
  html:
    css:
      - reference/_styles-quartodoc.css
    theme:
      - _extensions/catppuccin/mocha.scss



website:
  reader-mode: true
  title: "Integro-Difference Equation Models in Python-JAX"
  navbar:
    left:
      - text: "Home"
        href: ./index.qmd
      - text: "The Maths"
        href: ./site/mathematics.qmd
      - text: "Docs"
        href: ./reference/index.qmd
      - text: "Examples"
        href: ./site/examples.qmd
    tools:
      - icon: github
        menu:
          - text: "Source"
            href: https://github.com/tatephughes/JAX-IDEM
          - text: "Issues"
            href: https://github.com/tatephughes/JAX-IDEM/issues


lightbox: true

toc: true
number-sections: true

quartodoc:
  style: pkgdown
  sidebar: reference/_sidebar.yml
  package: jaxidem
  css: reference/_styles-quartodoc.css
  sections:
    - title: IDEM
      desc: The idem.Model class and surrounded classes and functions.
      contents:
        - idem.Model
        - idem.Model.fit_mle
    - title: Filtering Methods
      desc: Various forms of the Kalman filter, each with its own stability and performance profile. For more information, see [Filtering Scaling](../site/filtering_scaling.qmd).
      contents:
        - filters.kal_filter
        - filters.skal_filter
        - filters.inf_filter
        - filters.sqrt_filter
        - filters.sqinf_filter
        - filters.pkal_filter
    - title: Utilities
      desc: Utility functions to supplement the package. Includes a simple basis expansion system, a spatio-temporal data type, tools for testing jit-functions and so on.
      contents:
        - utils.Grid
        - utils.create_grid
        - utils.place_basis
        - utils.random_basis
        - utils.place_cosine_basis
        - utils.st_data
        - utils.pd_to_st
        - utils.time_jit
        - utils.flatten_and_unflatten
