[project]
name = "jax-idem"
version = "0.0.1"
authors = [
  { name="Evan Tate Paterson Hughes", email="etatephughes@gmail.com" },
]
description = "Integro-difference Equation Models for Python-JAX"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "jax>=0.4.13",
    "matplotlib>=3.7.5",
    "optax>=0.1.8",
    "pyqt5>=5.15.11",
    "ruff>=0.9.0",
    "seaborn>=0.13.2",
    "tqdm>=4.67.1",
]

[project.urls]
Homepage = "https://github.com/tatephughes/JAX-IDEM"
Issues = "https://github.com/tatephughes/JAX-IDEM/issues"
