---
title: "Synthetic Data Example"
---

# Simulation


# Simulation

We create a simple model with downward-movement and diffusion, on 400 cosine basis functions.

```{python}
#| output: false
#| eval: true

import jax
# Some filters, particularily the sqrt filters, may work in 32-bit, but expect instabilities.
jax.config.update("jax_enable_x64", True)
import jax.numpy as jnp

# Module imports
import jaxidem.utils as utils
import jaxidem.idem as idem
import jaxidem.filters as filts

seed = 4
key = jax.random.PRNGKey(seed)
keys = jax.random.split(key, 10)


T = 20
nobs = 400
process_basis = utils.place_cosine_basis(N=20) 

# This puts a point of mass at 0.1,0.9 and a point of 0 at 0.9, 0.1.
# Using the least squares estimator, this creates a point at the corner.
inp_data = jnp.array([[0.1, 0.9, 100],
                      [0.9, 0.1, 0]])


# create a 'ball' at the top left using least squares
PHI = process_basis.mfun(inp_data[:,0:2])
alpha_0 = jnp.linalg.pinv(PHI.T@PHI)@PHI.T @ inp_data[:,2]



# this function creates models like in this example. for practical uses, use `init_model`.

# Fudged numbers to look at least a little interesting.
K_basis = (
    utils.place_basis(nres=1, min_knot_num=1, basis_fun=lambda s, r: 1),
    utils.place_basis(nres=1, min_knot_num=1, basis_fun=lambda s, r: 1),
    utils.place_basis(nres=1, min_knot_num=1, basis_fun=lambda s, r: 1),
    utils.place_basis(nres=1, min_knot_num=1, basis_fun=lambda s, r: 1),
)
# These values create reasonable drift and diffusion at
s = 0.0001
k = (
    jnp.array([1/(2*jnp.pi*s)]), # Scale parameter    (θ_1)
    jnp.array([2*s]), # Shape paramter  (θ_2)
    jnp.array([-0.02]), # X-axis drift    (θ_3) 
    jnp.array([0.02]), # Y-axis drift     (θ_4)
)
kernel = idem.param_exp_kernel(K_basis, k)

model = idem.gen_example_idem(keys[0],
                              process_basis = process_basis,
                              beta = jnp.array([0.0]),
                              kernel=kernel)




coords = jax.random.uniform(
                keys[0],
                shape=(nobs, 2),
                minval=0,
                maxval=1,
            )
times = jnp.repeat(jnp.arange(1, T + 1), coords.shape[0])
rep_coords = jnp.tile(coords, (T, 1))
x = rep_coords[:,0]
y = rep_coords[:,1]


process_data, obs_data = model.simulate(keys[1], x, y, times, alpha_0 = alpha_0)

# For normalising axes
zmin = float(jnp.nanmin(obs_data.z))
zmax = float(jnp.nanmax(obs_data.z))
zbounds = [zmin, zmax]


```



```{python}
#| output: false
#| echo: false


import plotly.graph_objects as go
import plotly.figure_factory as ff
from plotly.subplots import make_subplots

# creates frames of scattered data
def plotly_st_scatter(st,
                      title="Spatio-Temporal Field",
                      colorscale="Viridis",
                      mark_size=5,
                      name='scatter',
                      zbounds = None,
                      ):

    T = st.T

    klass = go.Scattergl

    if zbounds is None:
        zmin = float(jnp.nanmin(st.z))
        zmax = float(jnp.nanmax(st.z))
    else:
        zmin = zbounds[0]
        zmax = zbounds[1]

    traces = []
    frames = []
    for t in range(T):
        x = st.coords_tree[t][:,0]
        y = st.coords_tree[t][:,1]
        z = st.zs_tree[t]

        trace = go.Scattergl(
            x=x.tolist(),
            y=y.tolist(),
            mode="markers",
            name=name,
            marker=dict(
                size = mark_size,
                color=z.tolist(),
                colorscale=colorscale,
                cmin=zmin,
                cmax=zmax,
                showscale=True
            ),
            showlegend=False
        )
        frames.append(go.Frame(name=str(t), data=[trace]))
        traces.append(trace)
        
    coloraxis = dict(
        colorscale=colorscale,
        cmin=float(zmin),
        cmax=float(zmax),
        colorbar=dict(title="z")  # customize as needed
    )
        
    return frames, traces




def make_interactive_fig(traces):

    fig = go.Figure()
    
    for trace in traces:
        fig.add_trace(trace)

    fig.data[10].visible = True

    steps = []
    for i in range(len(fig.data)):
        step = dict(
            method="update",
            args=[{"visible": [False] * len(fig.data)},
                  {"title": "Time: " + str(i)}],  # layout attribute
        )
        step["args"][0]["visible"][i] = True  # Toggle i'th trace to "visible"
        steps.append(step)

    sliders = [dict(
        active=10,
        currentvalue={"prefix": "T: "},
        pad={"t": 50},
        steps=steps
    )]
    
    fig.update_layout(
        sliders=sliders
    )
        
    return fig

import jaxidem.plotters as plotters

```

:::{.columns}
::: {.column width="50%"}
```{python}
frames, traces = plotly_st_scatter(process_data, title="Observations", mark_size=20, zbounds=zbounds)
process_fig = make_interactive_fig(traces)

# Apply the catppuccin mocha theme to match these notebooks
plotters.apply_catppuccin_mocha(process_fig, fontsize = 20)

process_fig.update_layout(
    xaxis=dict(showticklabels=False),
    yaxis=dict(showticklabels=False, scaleanchor="x")
)
 
process_fig.show()
```
:::
::: {.column width="50%"}

```{python}
frames, traces = plotly_st_scatter(obs_data, title="Observations", mark_size=20, zbounds=zbounds)
obs_fig = make_interactive_fig(traces)

# Apply the catppuccin mocha theme to match these notebooks
plotters.apply_catppuccin_mocha(obs_fig, fontsize = 20)

obs_fig.update_layout(
    xaxis=dict(showticklabels=False),
    yaxis=dict(showticklabels=False, scaleanchor="x")
)

obs_fig.show()
```
:::
:::


# Filtering and Sampling routine

We need a function to sample from the state conditional on the parameters.
This can be constructed using filtering and backwards sampling;

```{python}

import jax.lax as jl
import jax.random as jr
from jax.random import multivariate_normal as smvn
from jax.random import normal as snorm
from functools import partial
from jaxidem.utils import add_variance
from jax.scipy.linalg import solve

key = jax.random.PRNGKey(0)

filterer = model.get_filter(obs_data,
                            method="sikalman",
                            likelihood="none")
M = model.M
S2_eta = model.S2_eta
S2_eta_shape = model.S2_eta_shape

def sample_alphas(key, params):

    filt_results = filterer(params)

    ms = filt_results['ms']
    Ps = filt_results['Ps'] # Will need adjustment depending on the filter.

    def backsample(carry, x):

        alpha_tp = carry
        m_tt, P_tt, key = x

        mpred = M @ m_tt
        Ppred = add_variance(M @ P_tt @ M.T, S2_eta, S2_eta_shape)
        
        C = solve(Ppred, M @ P_tt).T

        alpha_t = smvn(key, m_tt + C @ (alpha_tp - mpred), P_tt - C @ Ppred @ C.T)
        
        return alpha_t, alpha_t

    keys = jr.split(key, ms.shape[0])
    
    xs = (jnp.flip(ms[:-1], axis=0),
          jnp.flip(Ps[:-1], axis=0),
          keys[1:])

    alpha_T = smvn(keys[0], ms[-1], Ps[-1])
    
    carry, seq = jl.scan(
        backsample,
        (alpha_T),
        xs,
    )

    return jnp.vstack([jnp.flip(seq, axis=0), alpha_T[None,:]])

key, alpha_key = jr.split(key, 2)

alphas = sample_alphas(alpha_key, model.params)
# do the test nerd

filt_results = filterer(model.params)
ms = filt_results['ms']
Ps = filt_results['Ps']
(
    log_S2_eta,
    log_S2_eps,
    ks,
    beta,
) = model.params

logks1, logks2, ks3, ks4 = ks
ks1 = jnp.exp(logks1)
ks2 = jnp.exp(logks2)
S2_eta = jnp.exp(log_S2_eta)
S2_eps = jnp.exp(log_S2_eps)
            
M = model.con_M((ks1, ks2, ks3, ks4))
            
m_post, P_post = filts.kal_smoother(ms, Ps, S2_eta, model.S2_eta_shape, M)


n = 10
keys = jr.split(key, n)

alphass = jl.map(lambda k: sample_alphas(k, model.params), keys)
means = jnp.mean(alphass, axis=0)

print("Average relative Tolerance:")
print(jnp.mean(((means - m_post)/m_post)))

```


For the variance terms, we need to sample from the inverse Wishart distribution; this is not built in to JAX, but the routine is simple; the following is adapted from [pybasicbayes]{https://github.com/mattjj/pybasicbayes};

```{python}
from jax.scipy.linalg import solve_triangular as st

# Note that nu and nu_0 are static

@partial(jax.jit, static_argnames=["nu"])
def sample_invwishart(key, S, nu):
    n = S.shape[0]
    chol = jnp.linalg.cholesky(S)
    x = jr.normal(key, shape=(nu,n))
    R = jnp.linalg.qr(x,'r')
    T = st(R.T,chol.T, lower=True).T
    return T @ T.T

# test; mean should be I_2

r = 2

vs = jax.vmap(sample_invwishart, in_axes=(0, None, None))

nu = r+2
S = jnp.array([[1,0.5],[0.5,1]])

keys = jr.split(key, 10000)

sample = vs(keys, S, nu)

print(jnp.mean(sample, axis=0))
# ye good enough
```



So, if we fit the prior

$$\begin{split}
\pi(\Sigma_{eta}) \sim\mathcal{W}^{-1}(\Psi_0, \nu_0)
\end{split}
$$

Then we can sample like

```{python}

nu_0 = model.nbasis+2 # I don't know enough about IW to give a good guess here
Psi_0 = S2_eta * jnp.eye(model.nbasis)

print(sample_invwishart(key, Psi_0, nu_0))

keys = jr.split(key, 1000)
# quick test to confirm mean is S2_eta
sample = vs(keys, Psi_0, nu_0)
# Average diagonal (should be 0.01)
print(jnp.mean(jnp.diag(jnp.mean(sample, axis=0))))


```


With easily verifiable and known conjugacy results, 

$$\begin{split}
\Sigma_eta \mid \alpha, Z, \theta, \Sigma_eps \sim \mathcal{W}^-1 [\Psi_\alpha + Psi_0, \nu + T]
\end{split}
$$

where

$$\begin{split}
\Psi_\alpha = \sum_{t=1}^T (\alpha_t - M_t^\theta\alpha_{t-1}(\alpha_t - M_t^\theta\alpha_{t-1}^\intercal)
\end{split}
$$


Finally, the last parameters are sampled with a metropolis scheme;

$$\begin{split}
p(\theta_\kappa\mid\cdot) \propto p(\theta_\kappa) \prod_{t=0}^T p(\alpha_t\mid \alpha_{t-1}, \cdot)
\end{split}
$$

defining this function, with a normal distribution prior on $\theta_\kappa$

```{python}

from jax.scipy.stats.multivariate_normal import logpdf as lpmvn
from jax.scipy.stats.norm import logpdf as lpnorm

init_tker = model.params.trans_kernel_params


@jax.jit
def kern_prior(tker_params):

    return (lpnorm(tker_params[0], init_tker[0], 1) 
            + lpnorm(tker_params[1], init_tker[1], 10)
            + lpnorm(tker_params[2], init_tker[2], 1)
            + lpnorm(tker_params[3], init_tker[3], 1))[0]


@jax.jit
def kern_post(tker_params, alphas, S2_eta):

    prior = kern_prior(tker_params)

    means = M @ alphas[1:].T

    proc_like = jnp.sum(jl.map(lambda x: lpmvn(x[0], x[1], S2_eta), (alphas[1:], means.T)))
    
    return prior + proc_like


#hmc = blackjax.hmc(lambda params: kern_post(params, alphas, S2_eta), step_size=1e-2,
#                   inverse_mass_matrix=jnp.ones(4),
#                   num_integration_steps=10)
#
#state = hmc.init(init_tker)

```


Lastly, an inverse-gamma sampler

```{python}

def sample_invgamma(key, alpha, beta):
    g = jr.gamma(key, alpha)/beta
    return 1/g

alpha = 2
lam = model.S2_eps

vs = jax.vmap(sample_invgamma, in_axes=(0, None, None))

keys = jr.split(key, 10000)

sample = vs(keys, alpha, lam)

print(jnp.mean(sample, axis=0))
# should be S2_eps = 0.01

```


Following {This guide}[https://blackjax-devs.github.io/blackjax/examples/howto_metropolis_within_gibbs.html],

```{python}
import blackjax
mwg_init_theta = blackjax.hmc.init
mwg_step_fn_theta = blackjax.hmc.build_kernel()

zs_tree = obs_data.zs_tree
X_obs_tree = obs_data.X_obs_tree
PHI_obs_tree = jax.tree.map(model.process_basis.mfun, obs_data.coords_tree)
sn = sum([z.size for z in zs_tree])


def square(vec): return jnp.inner(vec, vec)

T = obs_data.T

# S2_eta prior
alp_eta_0 = 2
lam_eta_0 = model.S2_eta
V = jnp.eye(model.nbasis)
# variance of process noise is S2_eta * V

# S2_eps prior
alp_eps_0 = 2
lam_eps_0 = model.S2_eps

# beta prior
p = model.beta.size
s2_beta_0 = 1
mu_beta_0 = model.beta


parameters = {"trans_kernel_params": {
        "inverse_mass_matrix": jnp.array([1., 1., 1., 1.]),
        "num_integration_steps": 100,
        "step_size": 1e-2
    }}

alphas_0 = alphas

initial_state = {
    "trans_kernel_params": mwg_init_theta(
        position=init_tker,
        logdensity_fn=lambda theta: kern_post(tker_params = theta,
                                              alphas=alphas_0,
                                              S2_eta=S2_eta)),
    "S2_eta": model.S2_eta,
    "S2_eps": model.S2_eps,
    "beta": model.params.beta,
    "alphas": alphas_0
}



state = initial_state

def mwg_kernel(key, state, pars):

    trans_theta = state['trans_kernel_params']
    S2_eta = state['S2_eta']
    S2_eps = state['S2_eps']
    beta = state['beta']
    alphas = state['alphas']

    key_theta, key_eta, key_eps, key_beta, key_alphas= jax.random.split(key, num=5)

    # Sample from theta using a HMC step
    
    def logdensity_theta(theta): return kern_post(tker_params = theta,
                                                  alphas=alphas,
                                                  S2_eta=S2_eta)
    # Doesn't this get recompiled at each step?
    
    state["trans_kernel_params"] = mwg_init_theta(
        position=trans_theta.position,
        logdensity_fn=logdensity_theta
        )
    # Not so sure about this code; isn't this mutation?
    state["trans_kernel_params"], _ = mwg_step_fn_theta(
        rng_key=key_theta,
        state=trans_theta,
        logdensity_fn=logdensity_theta,
        **parameters["trans_kernel_params"]
    )
    
    trans_theta = state['trans_kernel_params']


    # Sample from the variances with the conditional posteriors

    # process variance
    A = alphas[1:] - alphas[:-1] @ M.T
    #S = Psi_0 + A.T@A
    #nu = nu_0 + T
    #S2_eta = sample_invwishart(key_eta, S, nu)

    # Actually keep S2_eta scalar!

    alp = alp_eta_0 + 0.5*r*T
    lam = lam_eta_0 + 0.5*jnp.sum(jl.map(lambda a: a.T @ solve(V, a, assume_a="pos"), A))
    S2_eta = sample_invgamma(key_eta, alp, lam)
    state['S2_eta'] = S2_eta
    

    # observation variance
    alphas_tree = list(alphas[1:])
    
    square_diffs = jnp.array(jax.tree.map(lambda z,x,p,a: square(z - x@beta - p@a), zs_tree, X_obs_tree, PHI_obs_tree, alphas_tree))
    
    alp = alp_eps_0 + 0.5*sn
    lam = lam_eps_0 + 0.5 * jnp.sum(square_diffs)
    S2_eps = sample_invgamma(key_eps, alp, lam)
    state['S2_eps'] = S2_eps

    # Linear coeffients
    B = jnp.eye(p)/s2_beta_0 + jnp.sum(jnp.array(jax.tree.map(lambda x: x.T@x, X_obs_tree)))/S2_eps
    diffs = jax.tree.map(lambda z,x,p,a: x.T@(z - p @ a), zs_tree, X_obs_tree, PHI_obs_tree, alphas_tree)
    mu = solve(B, jnp.sum(jnp.array(diffs), axis=0), assume_a='pos')/S2_eps

    beta = solve(B, snorm(key_beta, shape = (p,)), assume_a='pos') + mu
    state['beta'] = beta
    
    # Sample from alphas using FFBS
    params = idem.IdemParams(
            log_S2_eps=jnp.log(S2_eps),
            log_S2_eta=jnp.log(S2_eta),
            trans_kernel_params=trans_theta.position,
            beta=beta,
        )
    state["alphas"] = sample_alphas(key_alphas, params)

    return state
    
```

Sampling loop

```{python}
def sampling_loop(key, initial_state, parameters, num_samples):
    
    @jax.jit
    def one_step(state, rng_key):
        state = mwg_kernel(
            key=rng_key,
            state=state,
            pars=parameters
        )
        return state, state

    keys = jax.random.split(key, num_samples)
    _, states = jax.lax.scan(one_step, initial_state, keys)

    return states

def sampling_loop_for(key, initial_state, parameters, num_samples):
    
    @jax.jit
    def one_step(state, rng_key):
        state = mwg_kernel(
            key=rng_key,
            state=state,
            pars=parameters
        )
        return state, state
    states_list = [initial_state]
    keys = jax.random.split(key, num_samples)    
    for i in range(num_samples):
        states_list.append(one_step(states_list[-1], keys[i])[0])

    states = jax.tree.map(
        lambda *xs: jnp.stack(xs, axis=0),
        *states_list[1:] # don't include last point
    )
        
    return states


num_samples = 20

states_A = sampling_loop(key, initial_state, pars, num_samples)
print(states_A['S2_eps'])
states_B = sampling_loop_for(key, initial_state, pars, num_samples)
print(states_A[0])

```
