---
title: "Sydney Radar Data"
author: "Evan Tate Paterson Hughes"
format:
  html:
    code-fold: false
    toc: true
    inclue-in-header: header.html
    mathjax: 
      extensions: ["breqn", "bm", "ams"]
jupyter: python3
bibliography: Bibliography.bib
---

::: {.content-visible unless-format="pdf"}

[Index](../index.html)

:::

# The Sydney Radar Data Set

This is a data set... [more information here and plotting here]

# Importing the relevant packages and Loading the data

Firstly, we load the relevant libraries and import the data.

```{python}

import jax
jax.config.update("jax_enable_x64", True)
import os
import jax.numpy as jnp
import jax.random as jr
import pandas as pd
import jaxidem.idem as idem
import jaxidem.utils as utils
import matplotlib.pyplot as plt
import jaxidem.plotters as plotters

radar_df = pd.read_csv('./data/radar_df.csv')

```

We should put this data into `jax-idem`s `st_data` type;

```{python}
#| output: false
radar_data = utils.pd_to_st(radar_df, 's2', 's1', 'time', 'z') 
```

## Plotting

There is an optional module for jaxidem, jaxidem.plotters (install it with `pip install jaxidem[plotters]`) that includes some built-in functions to make plots of various objects relating to modelling. 
Note that this module uses plotly to create interactive html-based plots, primarily for notebooks such as this.
For saving static images of plots, plotly requires kaleido, which itself requires chrome. 
This is the reason that this module is optional, but if you need to install chrome, you can use `plotly_get_chrome` in bash, assuming you are on linux.

The `plotters` module uses the functions `plotly_st_grid` or `plotly_st_scatter` (the former for gridded data, the latter for scattered data) to create a list of frames for each time point. 

The Sydney Radar data are 28x40 images, so we can use the grid version;

```{python}
import jaxidem.plotters as plotters

frames = plotters.plotly_st_grid(radar_data, title="Sydney Radar Data")
```

There are a few ways to then present this data; a static grid of each data points using `make_st_fig`, an interactive plot with a slider to see each time point using `make_interactive_fig`, and a gif using `save_st_gif`. 

To make an interactive plot,

```{python}
sydney_fig = plotters.make_interactive_fig(frames)

# Apply the catppuccin mocha theme to match these notebooks
plotters.apply_catppuccin_mocha(sydney_fig, fontsize = 20)

sydney_fig.update_layout(
    xaxis=dict(showticklabels=False),
    yaxis=dict(showticklabels=False, scaleanchor="x")
)

sydney_fig.show()
```

More options of plotting will be looked at when we do filtering, fitting, and inference on this model.


## Modelling

We will firstly censor the data, so that we can assess the 'blanks' we filled in.

For this example, we have 12 time points. 
We will remove the first, last, and one middle point, to test backcasting, intracasting and forecasting respectively.

Note that, in removing the middle time, our data now has 'varying' observation dimension (we have 28x40 observation points, one for each pixel, at every time point except the middle one, where we have 'dimension 0').
While there is no reason analytically that any Kalman filter variant cannot handle this kind of, case, this functionality is only implemented into the information filters (including the parallel filters) in `jax-idem`.
This is not a problem here however, as the observation dimension is generally much higher than the process dimensions we might choose, so the information filters are much more performant anyway.

```{python}
#| eval: true
# Censor the data!
radar_df_censored = radar_df
# remove the first time measurements (for backcast testing)
radar_df_censored = radar_df_censored[radar_df_censored['time'] != "2000-11-03 08:45:00"]
# remove the a specific time (for intracast testing)
radar_df_censored = radar_df_censored[radar_df_censored['time'] != "2000-11-03 09:25:00"]
# remove the a final two times (for forecast testing)
radar_df_censored = radar_df_censored[~radar_df_censored['time'].isin(["2000-11-03 10:15:00", "2000-11-03 10:05:00"])]
# three randomly chose indices ('dead pixels')

# no covariates (besides intercept)
radar_data = utils.pd_to_st(radar_df_censored, 's2', 's1', 'time', 'z')

# make a new plot to show the missing data

frames = plotters.plotly_st_grid(radar_data, title="Sydney Radar Data")

sydney_fig = plotters.make_st_fig(frames, spacing = [0.01, 0.1])

# Apply the catppuccin mocha theme to match these notebooks
plotters.apply_catppuccin_mocha(sydney_fig, fontsize = 20)

sydney_fig.update_xaxes(title_text=None, showticklabels=False)
sydney_fig.update_yaxes(title_text=None, showticklabels=False)

sydney_fig.update_layout(
    xaxis=dict(showticklabels=False),
    yaxis=dict(showticklabels=False, scaleanchor="x")
)

sydney_fig.show()
```

We now create an initial model for this data 

```{python}
#| output: false
#| eval: true
model = idem.init_model(data=radar_data)
```

This, by default, creates an invariant kernel model with no covariates beside an intercept, with cosine basis function for the process decomposition.
We can now get the marginal data likelihood function of this model with the `get_log_like` method;

```{python}
#| eval: true
log_marginal = model.get_log_like(radar_data, method="sqinf", likelihood='partial')
```

We can then use this function to do various inference techniques, like direclty maximising it or Bayesian MCMC methods. It is auto-differentiation compatible, so can easily be dropped into packages like `optax` or `blackjax` for these purposes.

The function takes, as an input, an object of type `IdemParams`, which is a `NamedTuple` containing the log variances, (transformed) kernel parameters, and the regression coefficients.
The `Model` class has a value of these paramters, `Model.params`, and a method is provided to print these parameters in a clear way;

```{python}
#| output: true
#| eval: true
idem.print_params(model.params)
```

## Maximum Likelihood Estimation

Once we have this marginal likelihood, there are a few ways to progress.
A good start is with a maximum likelihood method.
Obviously, we can no just take this lgo marginal function and maximise it in any way we see fit, but `jaxidem.Model` has a built-in method for this, `Model.fit_mle`. Given data, this will use a method from 'optax' to create a new output model with the fitted parameters.

```{python}
#| eval: false

import optax

fit_model_mle, mle_params = model.fit_mle(radar_data,
                                          optimizer = optax.adam(1e-2),
                                          max_its = 100,
                                          method = 'sqinf')

```

```{python}
#| eval: true
#| echo: false
#| output: false

import pickle
with open('./pickles/Hamilton/24_4_25/mle_params.pkl', 'rb') as file: 
    mle_params = pickle.load(file)
fit_model_mle = model.update(mle_params)
```

The resulting parameters are then

```{python}
#| eval: true
idem.print_params(mle_params)
```

Of course, we can use any other method to maximise this, by using whatever method desired on the function returned from `Model.get_log_liklehood`.
We can update the model with new parameters using the method `Model.update`, and `utils.flatten_and_unflatten` (see documentation) allows working with flat arrays instead of PyTrees if needed.

## Posterior Sampling

It is obviously desirable to use MCMC methods in order to sample from the posterior distribution.
This can be done manually using the log likelihood, or by using the method `Model.sample_posterior`. 
We need to provide it with a sampling kernel; that is, a method to get from one state to the next.


## Using Blackjax

From there, it is easy to sample from the posterior

```{python}
#| eval: false
import blackjax

key = jr.PRNGKey(1) # PRNG key
inverse_mass_matrix = jnp.ones(model.nparams)
num_integration_steps = 10
step_size = 1e-5

samp = blackjax.hmc(log_marginal,
                    step_size,
                    inverse_mass_matrix,
                    num_integration_steps)
step=samp.step
init = samp.init(mle_params)

def sampling_kernel(carry, i):
    nuts_key = jr.fold_in(key, i)
    new_state, info = step(nuts_key, carry)
    return new_state, (new_state, info)

sample, _ = model.sample_posterior(key,
                                   obs_data=radar_data,
                                   n=10,
                                   burnin=0,
                                   init=init,
                                   sampling_kernel=sampling_kernel)

sample_arr = jnp.column_stack(jax.tree.leaves(sample.position))

```

```{python}
#| eval: true
#| echo: false
#| output: false

import numpy as np
import matplotlib.pyplot as plt

csv_data = np.loadtxt('data/Chains/HMC_chain_32.csv', delimiter=',')
# Convert the NumPy array to a JAX array
sample_arr = jnp.array(csv_data)[10000:60000,1:]

```

```{python}
import plotly.graph_objects as go
from plotly.subplots import make_subplots

fig = make_subplots(rows=7, cols=1, shared_xaxes=True,
#                    subplot_titles=[f"Parameter {i+1}" for i in range(n_params)],
                    vertical_spacing=0.02)

for i in range(7):
    fig.add_trace(
        go.Scatter(y=sample_arr[:, i], mode='lines'),
        row=i+1, col=1
    )

plotters.apply_catppuccin_mocha(fig, fontsize=20)
fig.update_layout(height=200 * 7, width=800,
                  title_text="MCMC Trace Plots", showlegend=False)

fig.show()
```

Lets take the posterior mean for some filtering and predicting.

```{python}
#| eval: true
# gets the function used to go from a flat array to a parameter of the type used in the models
fparams, unflatten = utils.flatten_and_unflatten(model.params)

post_mean = jnp.mean(sample_arr, axis=0)
new_params = unflatten(post_mean)

new_model = model.update(new_params)

filt_data, fore_data, filt_results = new_model.filter(radar_data, forecast = 3, method="sqinf")
```

```{python}
#| output: true
#| eval: true
#filt_data.save_plot('figure/filtered_plot.png')
frames = plotters.plotly_st_grid(filt_data, title="Sydney Radar Datam filtered using the model")

filt_fig = plotters.make_st_fig(frames, spacing = [0.01, 0.1])

# Apply the catppuccin mocha theme to match these notebooks
plotters.apply_catppuccin_mocha(filt_fig, fontsize = 20)

filt_fig.update_xaxes(title_text=None, showticklabels=False)
filt_fig.update_yaxes(title_text=None, showticklabels=False)

filt_fig.update_layout(
    xaxis=dict(showticklabels=False),
    yaxis=dict(showticklabels=False, scaleanchor="x"),
)

filt_fig.show()
```


We've also forecasted the next 3 time points, and we can get them like this

```{python}
#| eval: true
#| output: true
#fore_data.save_plot('figure/fore_plot.png')
frames = plotters.plotly_st_grid(fore_data, title="Sydney Radar Data forecasted using the model")

fore_fig = plotters.make_st_fig(frames, spacing = [0.01, 0.1])

# Apply the catppuccin mocha theme to match these notebooks
plotters.apply_catppuccin_mocha(fore_fig, fontsize = 20)

fore_fig.update_xaxes(title_text=None, showticklabels=False)
fore_fig.update_yaxes(title_text=None, showticklabels=False)

fore_fig.update_layout(
    xaxis=dict(showticklabels=False),
    yaxis=dict(showticklabels=False, scaleanchor="x"),
    height = 200
)

fore_fig.show()

```


## Filter Comparison

The radar dataset is 'complete', that is, there is no missing data and each location has an observation at every single time point; in practice, this means that the observation dimension is constant.
This is important; in Python-JAX it is prefered that data is stored as arrays (tensors), which cannot be 'jagged' (where each row/column can have varying dimension). 
This can often be circumvented using PyTrees (a catch all term JAX uses to refer to 'container-like' data structures such as lists or tuples, which contain arrays), and indeed is done in the information filter, square-root information filter, and parallel filter (though this does incur a performance cost).
The same trick cannot been used for the kalman filters, since scan operations do not fully support PyTrees.

With that said, JAX-IDEM only supports missing data/changing data shape is only supported for the former filters.
To compare the filters, then, we need to use the uncensored data;

```{python}
radar_df = pd.read_csv('./data/radar_df.csv')
```

Now, re-initialising the model, the method `get_log_likelihood` handles these cases, and so we can get likelihoods using each of the filters, in order to compare.

```{python}
#| eval: true
#| output: false

import pandas as pd
key = jr.PRNGKey(1) # PRNG key

radar_data = utils.pd_to_st(radar_df, 's2', 's1', 'time', 'z') 
model = idem.init_model(data=radar_data, basis_type = 'cosine', basis_args=[20])

log_marginal_kal = model.get_log_like(radar_data, method="kalman", likelihood='full')
log_marginal_skal = model.get_log_like(radar_data, method="skalman", likelihood='full')
log_marginal_ikal = model.get_log_like(radar_data, method="ikalman", likelihood='full')
log_marginal_sqrt = model.get_log_like(radar_data, method="sqrt", likelihood='full')
log_marginal_inf = model.get_log_like(radar_data, method="inf", likelihood='full')
log_marginal_sqinf = model.get_log_like(radar_data, method="sqinf", likelihood='full')
log_marginal_pkal = model.get_log_like(radar_data, method="parallel", likelihood='full')
log_marginal_psqrt = model.get_log_like(radar_data, method="psqrt", likelihood='full')

nreps = 5

time_kal   = utils.time_jit(key, log_marginal_kal, model.params, n=nreps)
time_skal   = utils.time_jit(key, log_marginal_skal, model.params, n=nreps)
time_ikal   = utils.time_jit(key, log_marginal_ikal, model.params, n=nreps)
time_sqrt  = utils.time_jit(key, log_marginal_sqrt, model.params, n=nreps)
time_inf   = utils.time_jit(key, log_marginal_inf, model.params, n=nreps)
time_sqinf = utils.time_jit(key, log_marginal_sqinf, model.params, n=nreps)
time_pkal  = utils.time_jit(key, log_marginal_pkal, model.params, n=nreps)
time_psqrt  = utils.time_jit(key, log_marginal_psqrt, model.params, n=nreps)

data = [
    ["kal", time_kal.compile_time, time_kal.average_time * 1000, time_kal.value],
    ["skal", time_skal.compile_time, time_skal.average_time * 1000, time_skal.value],
    ["ikal", time_ikal.compile_time, time_ikal.average_time * 1000, time_ikal.value],
    ["inf", time_inf.compile_time, time_inf.average_time * 1000, time_inf.value],
    ["sqrt", time_sqrt.compile_time, time_sqrt.average_time * 1000, time_sqrt.value],
    ["sqinf", time_sqinf.compile_time, time_sqinf.average_time * 1000, time_sqinf.value],
    ["pkal", time_pkal.compile_time, time_pkal.average_time * 1000, time_pkal.value],
    ["psqrt", time_psqrt.compile_time, time_psqrt.average_time * 1000, time_psqrt.value],
]

df = pd.DataFrame(data, columns=["Method", "Compile Time (s)", "Average Time (ms)", "Log Likelihood"])

```

```{python}
#| eval: true
#| output: true

print(f"Results for IDEM with nbasis={model.nbasis}")
print(f"Precision: {model.M.dtype}")

print(df.to_markdown(index=False))
```
