# filters.sqrt_filter { #jaxidem.filters.sqrt_filter }

`filters.sqrt_filter`



## Functions

| Name | Description |
| --- | --- |
| [sqrt_filter](#jaxidem.filters.sqrt_filter.sqrt_filter) | The Square-Root Kalman Filter. |

### sqrt_filter { #jaxidem.filters.sqrt_filter.sqrt_filter }

```python
filters.sqrt_filter.sqrt_filter(
    m_0,
    U_0,
    M,
    PHI,
    S2_eta,
    S2_eps,
    zs_tree,
    S2_eta_shape,
    S2_eps_shape,
    forecast=0,
    likelihood='full',
)
```

The Square-Root Kalman Filter.

#### Parameters {.doc-section .doc-section-parameters}

| Name         | Type                                                              | Description                                                                                                                                                                                                 | Default    |
|--------------|-------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------|
| m_0          | Float\[Array, r\]                                                 | Prior mean of the filter at T=0.                                                                                                                                                                            | _required_ |
| U_0          | Float\[Array, \'r r\'\]                                           | Prior upper-triangular Cholesky factor of the state covariance at T=0.                                                                                                                                      | _required_ |
| M            | Float\[Array, \'r r\'\]                                           | State-transition matrix.                                                                                                                                                                                    | _required_ |
| PHI          | Float\[Array, \'n r\'\]                                           | Observation matrix.                                                                                                                                                                                         | _required_ |
| S2_eta       | Float\[Array, 1\] \| Float\[Array, r\] \| Float\[Array, \'r r\'\] | Process noise variance. Can be of shape (1,) (for scalar/i.i.d.), shape (r,) (for uncorrelated noise), or shape (r, r) (for correlated noise).                                                              | _required_ |
| S2_eps       | Float\[Array, 1\] \| Float\[Array, n\] \| Float\[Array, \'n n\'\] | Observation noise variance. Can be of shape (1,) (for scalar/i.i.d. noise), shape (n,) (for uncorrelated noise), or shape (n, n) (for correlated noise).                                                    | _required_ |
| zs_tree      | PyTree\[Float\[Array, n\]\]                                       | Observed data values. For the square-root filter, each observation must have the same dimension and use the same observation matrix.                                                                        | _required_ |
| S2_eta_shape | int                                                               | Shape code for `S2_eta` (needed for JIT compilation); 0 is scalar/i.i.d., 1 is vector/uncorrelated, 2 is matrix/correlated. Must match the dimensionality of `S2_eta`.                                      | _required_ |
| S2_eps_shape | int                                                               | Shape code for `S2_eps` (needed for JIT compilation); 0 is scalar/i.i.d., 1 is vector/uncorrelated, 2 is matrix/correlated. Must match the dimensionality of `S2_eps`.                                      | _required_ |
| forecast     | int                                                               | Number of time points to forecast ahead.                                                                                                                                                                    | `0`        |
| likelihood   | Literal\[\'none\', \'partial\', \'full\'\]                        | Log-likelihood computation mode. Must be one of 'none' (no likelihood is computed), 'partial' (likelihood computed up to an additive constant), or 'full' (full likelihood is computed). Default is 'full'. | `'full'`   |

#### Returns {.doc-section .doc-section-returns}

| Name         | Type        | Description                  |
|--------------|-------------|------------------------------|
| filt_results | SqrtResults | For details see Notes below. |

#### Notes {.doc-section .doc-section-notes}

The return type is SqrtResults, containing:

    - `ll` : float
      Log-likelihood value (possibly up to an additive constant).

    - `ms` : PyTree[Float[Array, "T r"]]
      Posterior means at each time step.

    - `Us` : PyTree[Float[Array, "T r r"]]
      Posterior square-roots of the state covariance at each time step.
      (Small note; these are not necessarily the cholesky factors!)

    - `m_preds` : PyTree[Float[Array, "T r"]]
      Predicted means at each time step.

    - `U_preds` : PyTree[Float[Array, "T r r"]]
      Predicted square-roots of the state covariance at each time step.

    - `m_forecast` : Float[Array, "forecast r"]
      Forecast means.

    - `U_forecast` : Float[Array, "forecast r r"]
      Forecast square-roots of the state covariance.

Symbolic dimensions:

    - `r` : state dimension
    - `n` : observation dimension
    - `T` : number of time steps
    - `forecast` : number of forecast steps