# Function reference {.doc .doc-index}

## Filtering and Smoothing Functions

Functions to apply Kalman/information filters, smoothers and so on.

| | |
| --- | --- |
| [kalman_filter](kalman_filter.qmd#jax_idem.filter_smoother_functions.kalman_filter) | Applies the Kalman Filter to a wide-format matrix of data. |
| [kalman_filter_indep](kalman_filter_indep.qmd#jax_idem.filter_smoother_functions.kalman_filter_indep) | Applies the Kalman Filter to a wide-format matrix of data. |
| [information_filter](information_filter.qmd#jax_idem.filter_smoother_functions.information_filter) |     Applies the Information Filter to a PyTree of data. |
| [information_filter_indep](information_filter_indep.qmd#jax_idem.filter_smoother_functions.information_filter_indep) |     Applies the Information Filter to a PyTree of data. |
| [kalman_smoother](kalman_smoother.qmd#jax_idem.filter_smoother_functions.kalman_smoother) | NOT FULLY IMPLEMENTED |

## Integro-Difference Models in JAX

Classes and functions to perform simulation, fitting, filtering and prediction on IDEMs.

| | |
| --- | --- |
| [Kernel](Kernel.qmd#jax_idem.IDEM.Kernel) | Generic class defining a kernel, or a basis expansion of a kernel with |
| [IDEM_Model](IDEM_Model.qmd#jax_idem.IDEM.IDEM_Model) | The Integro-differential Equation Model. |
| [param_exp_kernel](param_exp_kernel.qmd#jax_idem.IDEM.param_exp_kernel) | Creates a kernel in the style of AZM's R-IDE package |
| [simIDEM](simIDEM.qmd#jax_idem.IDEM.simIDEM) | Simulates from a IDE model. |
| [gen_example_idem](gen_example_idem.qmd#jax_idem.IDEM.gen_example_idem) | Creates an example IDE model, with randomly generated kernel on the |
| [basis_params_to_st_data](basis_params_to_st_data.qmd#jax_idem.IDEM.basis_params_to_st_data) | Converts the process expansion coefficients back into the original process |

## Utilties

General classes and functions used to supplement the main package

| | |
| --- | --- |
| [Grid](Grid.qmd#jax_idem.utilities.Grid) | A simple grid class to store (currently exclusively regular) grids, along |
| [Basis](Basis.qmd#jax_idem.utilities.Basis) | A simple class for spatial basis expansions. |
| [create_grid](create_grid.qmd#jax_idem.utilities.create_grid) | Creates an n-dimensional grid based on the given bounds and deltas. |
| [outer_op](outer_op.qmd#jax_idem.utilities.outer_op) | Computes the outer operation of two vectors, a generalisation of the outer |
| [bisquare](bisquare.qmd#jax_idem.utilities.bisquare) | Generic bisquare function |
| [place_basis](place_basis.qmd#jax_idem.utilities.place_basis) | Distributes knots (centroids) and scales for basis functions over a |
| [st_data](st_data.qmd#jax_idem.utilities.st_data) | For storing spatio-temporal data and appropriate methods for plotting such |