# utils.st_data { #jaxidem.utils.st_data }

```python
utils.st_data(x, y, times, z, dt=None, covariates=None, covariate_labels=None)
```

For storing spatio-temporal data and appropriate methods for plotting such
data, and converting between long and wide formats.

NEEDS MUCH MORE DOCUMENTATION

## Methods

| Name | Description |
| --- | --- |
| [as_wide](#jaxidem.utils.st_data.as_wide) | THIS METHOD IS LIMITED; SEEMS TO GET AN ERROR WITH RELATIVELY LOW DIMENSIONS! |
| [save_gif](#jaxidem.utils.st_data.save_gif) | UNIMPLEMENTED |

### as_wide { #jaxidem.utils.st_data.as_wide }

```python
utils.st_data.as_wide()
```

THIS METHOD IS LIMITED; SEEMS TO GET AN ERROR WITH RELATIVELY LOW DIMENSIONS!

Will likely need to implement in a different way, prehaps forgoeing jax
methods.
For now, this is simply only applied sparingly, in idem.kal_filter
for observation dimension, for example.

Gives the data in wide format. Any missing data will be represented in
the returned matrix as NaN.

#### Returns {.doc-section .doc-section-returns}

| Name   | Type                                                               | Description   |
|--------|--------------------------------------------------------------------|---------------|
|        | A dictionary containing the x coordinates and y coordinates as JAX |               |
|        | arrays, and a matrix corresponding to the value of the process at  |               |
|        | each time point (columns) and spatial point (rows).                |               |

### save_gif { #jaxidem.utils.st_data.save_gif }

```python
utils.st_data.save_gif()
```

UNIMPLEMENTED